# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Solderless'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["solderless_left", "solderless_right", "settings_reset"]'
      branches: '["bobobo1618/zmk/oledandcorne"]'

